<a href="https://colab.research.google.com/github/jhlopesalves/eda_humanidades/blob/main/encontro_4/enc_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encontro 4: Introdução a Pandas & NumPy

**Instrutor:** Jhonatan Lopes

## 1. Importando bibliotecas

Utilizaremos duas bibliotecas:

- `numpy`, importada como `np`;
- `pandas`, importada como `pd`.

Esses 'aliases' são convenções muito comuns em ciência de dados.

In [1]:
import numpy as np
import pandas as pd

Documentação oficial NumPy (Recomendo que explore a documentação, é extremamente

```text

Nos encontros anteriores, trabalhamos com objetos básicos de Python:

- strings;
- listas;
- dicionários;
- loops;
- funções.
```

## 2. De listas para `np.arrays`

Até aqui, utilizamos **listas** e **dicionários** para armazenar sequências de valores. Essas estruturas são bastante flexíveis e atendem bem a tarefas gerais, mas apresentam limitações importantes quando o objetivo é realizar **cálculos numéricos em larga escala**.

Para superar essas limitações, a biblioteca **NumPy** introduz uma nova estrutura de dados: o **`array`** (ou *ndarray*, *n-dimensional array*). Trata-se de um "container" **homogêneo**; todos os elementos têm o mesmo tipo; o que permite executar operações numéricas de maneira muito mais rápida e econômica do que com listas.

A partir dessa estrutura surge o conceito central do encontro: a **vetorização**.

> **Vetorização** é a prática de aplicar uma operação a um conjunto inteiro de valores de uma só vez, sem precisar escrever um loop explícito sobre cada elemento.

Em vez de pensarmos *"para cada elemento da sequência, faça X"*, passamos a pensar *"faça X sobre toda a sequência"*.

In [2]:
lista_de_numeros = [4, 7, 3, 9, 5]

array_de_numneros = np.array(lista_de_numeros)

print(lista_de_numeros)
display(array_de_numneros)
print(type(array_de_numneros))

[4, 7, 3, 9, 5]

array([4, 7, 3, 9, 5])

<class 'numpy.ndarray'>

In [3]:
# Em uma lista comum, esta operação não soma 1 a cada elemento.
print(lista_de_numeros * 2)

# Em um array NumPy, a operação é aplicada elemento por elemento.
display(array_de_numneros * 2)
display(array_de_numneros + 1)
display(array_de_numneros > 5)

[4, 7, 3, 9, 5, 4, 7, 3, 9, 5]

array([ 8, 14,  6, 18, 10])

array([ 5,  8,  4, 10,  6])

array([False,  True, False,  True, False])

A diferença importante:

- em listas Python, `lista * 2` repete a lista;
- em arrays NumPy, `array * 2` multiplica cada valor por 2.

In [4]:
print(np.mean(array_de_numneros))
print(np.median(array_de_numneros))
print(np.min(array_de_numneros))
print(np.max(array_de_numneros))

5.6
5.0
3
9

## 3. Um dicionário como registro

Um dicionário pode representar uma unidade de observação.

Neste exemplo, a unidade de observação é uma obra.

As chaves do dicionário são as variáveis:
```
- autor;
- título;
- área;
- ano;
- número de tokens;
- número de types.
```

In [5]:
obra = {
        "autor": "John Tukey",
        "titulo": "Exploratory Data Analysis",
        "area": "estatística",
        "ano": 1977,
        "n_tokens": 125_00,
        "n_types": 10_900,
        "n_sentencas": 5_200,
}

obra

{'autor': 'John Tukey',
 'titulo': 'Exploratory Data Analysis',
 'area': 'estatística',
 'ano': 1977,
 'n_tokens': 12500,
 'n_types': 10900,
 'n_sentencas': 5200}

In [6]:
print(obra["autor"])
print(obra["titulo"])
print(obra["n_tokens"])

John Tukey
Exploratory Data Analysis
12500

In [7]:
print(obra.keys())
print(obra.values())

dict_keys(['autor', 'titulo', 'area', 'ano', 'n_tokens', 'n_types', 'n_sentencas'])
dict_values(['John Tukey', 'Exploratory Data Analysis', 'estatística', 1977, 12500, 10900, 5200])

In [8]:
print(f"{obra["titulo"]} foi publicado em {obra["ano"]}.")

Exploratory Data Analysis foi publicado em 1977.

## 4. Uma lista de dicionários

Um dicionário representa uma obra.

Uma lista de dicionários representa várias obras.

Essa estrutura é muito útil porque cada dicionário continua agrupando as informações de uma única linha.

Em outras palavras:
```
- cada dicionário será uma linha;
- cada chave será uma coluna;
- cada valor será uma célula.
```

In [10]:
obras = [
    {
        "autor": "John Tukey",
        "titulo": "Exploratory Data Analysis",
        "area": "estatística",
        "ano": 1977,
        "n_tokens": 125_000,
        "n_types": 10_900,
    },
    {
        "autor": "Robert Merton",
        "titulo": "The Normative Structure of Science",
        "area": "sociologia",
        "ano": 1942,
        "n_tokens": 7_600,
        "n_types": 2_650,
    },
    {
        "autor": "Karl Popper",
        "titulo": "The Logic of Scientific Discovery",
        "area": "filosofia",
        "ano": 1934,
        "n_tokens": 155_000,
        "n_types": 12_800,
    },
]
obras

[{'autor': 'John Tukey',
  'titulo': 'Exploratory Data Analysis',
  'area': 'estatística',
  'ano': 1977,
  'n_tokens': 125000,
  'n_types': 10900},
 {'autor': 'Robert Merton',
  'titulo': 'The Normative Structure of Science',
  'area': 'sociologia',
  'ano': 1942,
  'n_tokens': 7600,
  'n_types': 2650},
 {'autor': 'Karl Popper',
  'titulo': 'The Logic of Scientific Discovery',
  'area': 'filosofia',
  'ano': 1934,
  'n_tokens': 155000,
  'n_types': 12800}]

## 5. Transformando registros em tabela

Agora transformaremos nossa lista de dicionários em um `DataFrame`.

Um `DataFrame` é uma tabela em pandas.

A função `pd.DataFrame()` recebe os dados e organiza tudo em linhas e colunas.

In [11]:
obras_df = pd.DataFrame(data=obras)

obras_df

,autor,titulo,area,ano,n_tokens,n_types
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,10900
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,12800

## 6. Adicionando uma nova obra

Como `obras` é uma lista, podemos adicionar mais um dicionário com `.append()`.

Depois, recriamos o DataFrame para visualizar a tabela atualizada.

In [12]:
obras = [
    {
        "autor": "John Tukey",
        "titulo": "Exploratory Data Analysis",
        "area": "estatística",
        "ano": 1977,
        "n_tokens": 125_000,
        "n_types": 35_900,
    },
    {
        "autor": "Robert Merton",
        "titulo": "The Normative Structure of Science",
        "area": "sociologia",
        "ano": 1942,
        "n_tokens": 7_600,
        "n_types": 2_650,
    },
    {
        "autor": "Karl Popper",
        "titulo": "The Logic of Scientific Discovery",
        "area": "filosofia",
        "ano": 1934,
        "n_tokens": 155_000,
        "n_types": 42_800,
    },
]

nova_obra = {
    "autor": "Machado de Assis",
    "titulo": "Memórias Póstumas de Brás Cubas",
    "area": "literatura",
    "ano": 1881,
    "n_tokens": 64_000,
    "n_types": 30_300,
}

obras.append(nova_obra)

obras_df = pd.DataFrame(data=obras)

obras_df

,autor,titulo,area,ano,n_tokens,n_types
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,42800
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,30300

## 7. Inspecionando o DataFrame

Antes de qualquer cálculo, precisamos inspecionar a tabela.

Perguntas iniciais:

```
- quantas linhas e colunas temos?
- quais são as colunas?
- quais colunas são numéricas?
- os dados parecem fazer sentido?
```
Inspecionar sempre precede interpretar, **SEMPRE** no sentido de **SEMPRE**!

In [13]:
obras_df.head()

,autor,titulo,area,ano,n_tokens,n_types
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,42800
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,30300

In [14]:
obras_df.shape

(4, 6)

In [15]:
obras_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   autor     4 non-null      object
 1   titulo    4 non-null      object
 2   area      4 non-null      object
 3   ano       4 non-null      int64
 4   n_tokens  4 non-null      int64
 5   n_types   4 non-null      int64
dtypes: int64(3), object(3)
memory usage: 324.0+ bytes

In [16]:
obras_df.describe()

               ano      n_tokens       n_types
count     4.000000       4.00000      4.000000
mean   1933.500000   87900.00000  27912.500000
std      39.669468   65569.60678  17600.491234
min    1881.000000    7600.00000   2650.000000
25%    1920.750000   49900.00000  23387.500000
50%    1938.000000   94500.00000  33100.000000
75%    1950.750000  132500.00000  37625.000000
max    1977.000000  155000.00000  42800.000000

## 8. Criando uma coluna derivada: TTR

Podemos criar novas colunas a partir de colunas existentes.

Aqui vamos calcular a TTR:

$$
\text{TTR} = \frac{\text{número de types}}{\text{número de tokens}}
$$

In [18]:
obras_df["ttr"] = obras_df["n_types"] / obras_df["n_tokens"]

obras_df[["titulo", "n_tokens", "n_types", "ttr"]]

                               titulo  n_tokens  n_types       ttr
0           Exploratory Data Analysis    125000    35900  0.287200
1  The Normative Structure of Science      7600     2650  0.348684
2   The Logic of Scientific Discovery    155000    42800  0.276129
3     Memórias Póstumas de Brás Cubas     64000    30300  0.473438

In [19]:
n_sentencas = [5_200, 415, 5_950, 3_500]

obras_df["n_sentencas"] = n_sentencas

obras_df

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900,0.287200,5200
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650,0.348684,415
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,42800,0.276129,5950
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,30300,0.473438,3500

In [20]:
obras_df["tokens_por_sentenca"] = (
    obras_df["n_tokens"] / obras_df["n_sentencas"]
)

obras_df[["titulo", "n_tokens", "n_sentencas", "tokens_por_sentenca"]]

,titulo,n_tokens,n_sentencas,tokens_por_sentenca
0,Exploratory Data Analysis,125000,5200,24.038462
1,The Normative Structure of Science,7600,415,18.313253
2,The Logic of Scientific Discovery,155000,5950,26.050420
3,Memórias Póstumas de Brás Cubas,64000,3500,18.285714

## 9.  Criando categorias com `np.where()`

O `np.where()` cria valores diferentes dependendo de uma condição.

A estrutura é:
`np.where(condição, valor_se_true, valor_se_falso)`

In [21]:
obras_df["classe_tamanho"] = np.where(
    obras_df["n_tokens"] >= 100_000, # condição
    "longo", # se a condição for verdadeira
    "curto", # se a condição for falsa
)

obras_df

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas,tokens_por_sentenca,classe_tamanho
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900,0.287200,5200,24.038462,longo
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650,0.348684,415,18.313253,curto
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,42800,0.276129,5950,26.050420,longo
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,30300,0.473438,3500,18.285714,curto

## 10. Usando `.loc`

O `.loc` permite escolher linhas e colunas de forma explícita.

A estrutura é:

```python
df.loc[linhas, colunas]

In [22]:
mascara = obras_df["n_tokens"] >= 100_000

mascara

0     True
1    False
2     True
3    False
Name: n_tokens, dtype: bool

In [23]:
obras_df[mascara]

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas,tokens_por_sentenca,classe_tamanho
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900,0.287200,5200,24.038462,longo
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,42800,0.276129,5950,26.050420,longo

In [24]:
obras_df[obras_df["area"] == "estatística"]

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas,tokens_por_sentenca,classe_tamanho
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900,0.2872,5200,24.038462,longo

`.loc[]` nos permite filtrar, selecionar colunas de interesse em uma única operação.

In [25]:
obras_df.loc[
    obras_df["ttr"] > 0.3,
    ["autor", "titulo", "n_tokens", "ttr"],
]

              autor                              titulo  n_tokens       ttr
1     Robert Merton  The Normative Structure of Science      7600  0.348684
3  Machado de Assis     Memórias Póstumas de Brás Cubas     64000  0.473438

## 11. Ordenando dados

Podemos ordenar por uma coluna usando `.sort_values()`.

O argumento `by` indica a coluna usada para ordenar.

O argumento `ascending=False` coloca os maiores valores primeiro.

In [26]:
obras_df.sort_values(by="n_tokens", ascending=False)

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas,tokens_por_sentenca,classe_tamanho
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,42800,0.276129,5950,26.050420,longo
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900,0.287200,5200,24.038462,longo
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,30300,0.473438,3500,18.285714,curto
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650,0.348684,415,18.313253,curto

In [27]:
obras_df.sort_values(by="ttr", ascending=True)

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas,tokens_por_sentenca,classe_tamanho
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,42800,0.276129,5950,26.050420,longo
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,35900,0.287200,5200,24.038462,longo
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650,0.348684,415,18.313253,curto
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,30300,0.473438,3500,18.285714,curto

## 12. Contando categorias

Usamos `.value_counts()` para isso.

In [28]:
obras_df["area"].value_counts()

area
estatística    1
sociologia     1
filosofia      1
literatura     1
Name: count, dtype: int64

In [29]:
obras_df["classe_tamanho"].value_counts()

classe_tamanho
longo    2
curto    2
Name: count, dtype: int64

## 13. Agrupando dados

Agrupar significa separar os dados por categorias e calcular uma métrica dentro de cada grupo.

A pergunta geral é:

> como uma medida muda de um grupo para outro?

A estrutura básica é:

```python
df.groupby("grupo")["coluna_numerica"].metrica()

Leia da direita pra esquerda:
> A média do número de tokens agrupado pela 'classe_tamanho'

In [30]:
obras_df.groupby("classe_tamanho")["n_tokens"].mean()

classe_tamanho
curto     35800.0
longo    140000.0
Name: n_tokens, dtype: float64

In [32]:
# Utilizando "named aggregations" (agregações nomeadas)
# A estrutura é: nome_da_nova_coluna=("coluna_original", "metrica")
obras_df.groupby("classe_tamanho").agg(
    # Conta a quantidade de obras (títulos) em cada grupo
    n_obras=("titulo", "count"),

    # Calcula a média da coluna 'n_tokens' para cada grupo
    media_tokens=("n_tokens", "mean"),

    # Calcula a média da coluna 'ttr' para cada grupo
    media_ttr=("ttr", "mean"),
)

                n_obras  media_tokens  media_ttr
classe_tamanho
curto                 2       35800.0   0.411061
longo                 2      140000.0   0.281665