<a href="https://colab.research.google.com/github/jhlopesalves/eda_humanidades/blob/main/encontro_4/enc_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Encontro 4: Introdução a NumPy e pandas

**Instrutor:** Jhonatan Lopes

## 1. NumPy e pandas

Neste encontro, utilizaremos duas bibliotecas centrais para análise de dados em
Python:

- **NumPy**, importada convencionalmente como `np`;
- **pandas**, importada convencionalmente como `pd`.

As formas abreviadas `np` e `pd` são aliases: nomes associados às bibliotecas
durante a importação. Essas convenções são amplamente utilizadas na
documentação e no código da comunidade científica em Python.

In [1]:
import numpy as np
import pandas as pd

### Documentação de referência

A documentação oficial das duas bibliotecas inclui introduções concisas aos
recursos utilizados neste curso:

- **NumPy - *The absolute basics for beginners***:
  [numpy.org/doc/stable/user/absolute_beginners.html](https://numpy.org/doc/stable/user/absolute_beginners.html)
- **pandas - *10 minutes to pandas***:
  [pandas.pydata.org/docs/user_guide/10min.html](https://pandas.pydata.org/docs/user_guide/10min.html)

Esses materiais apresentam arrays, DataFrames, indexação, operações
vetorizadas, agregações, agrupamentos e entrada e saída de dados.

A documentação oficial funciona também como referência para objetos e
operações encontrados posteriormente. A habilidade de localizar uma operação,
examinar sua interface e consultar exemplos faz parte do uso regular dessas
bibliotecas.

## 2. Arrays NumPy e operações vetorizadas

Listas Python permitem armazenar sequências de objetos e são adequadas para uma
grande variedade de tarefas. Para cálculos numéricos, NumPy fornece uma
estrutura especializada: o **`ndarray`**, ou array multidimensional.

Um array NumPy possui um `dtype` que descreve como seus elementos são
representados. Em arrays numéricos, isso permite armazenar e processar valores
de maneira uniforme e utilizar operações implementadas especificamente para
computação numérica.

Uma característica central dessa representação é a **vetorização**. Em vez de
escrever explicitamente um loop Python para aplicar a mesma operação a cada
valor, a operação pode ser expressa diretamente sobre o array inteiro.

Por exemplo, multiplicar um array por `2` produz um novo array em que cada
elemento foi multiplicado por `2`. Comparações também podem ser vetorizadas,
produzindo um valor Booleano para cada posição do array.

Em operações numéricas, essa forma de computação costuma ser mais concisa e
pode aproveitar implementações otimizadas fornecidas pelo NumPy.

In [2]:
lista_de_numeros = [4, 7, 3, 9, 5]

array_de_numeros = np.array(lista_de_numeros)

print(lista_de_numeros)
display(array_de_numeros)
print(type(array_de_numeros))

[4, 7, 3, 9, 5]

array([4, 7, 3, 9, 5])

<class 'numpy.ndarray'>

A mesma expressão pode ter comportamentos diferentes de acordo com o tipo do
objeto.

Para uma lista Python, `lista_de_numeros * 2` repete a sequência. Para um array
NumPy, `array_de_numeros * 2` multiplica cada elemento por `2`.

A expressão `array_de_numeros + 1` também opera elemento a elemento. Já
`array_de_numeros > 5` compara cada valor com `5` e produz um array de valores
Booleanos nas posições correspondentes.

As três operações sobre o array são exemplos de operações vetorizadas.

Nos exemplos, `print` mostra apenas os valores, enquanto `display` mostra a
representação completa do objeto, como `array([...])`. Essa representação torna
visível o tipo da estrutura com que estamos trabalhando.

In [3]:
print(lista_de_numeros * 2)

display(array_de_numeros * 2)
display(array_de_numeros + 1)
display(array_de_numeros > 5)

[4, 7, 3, 9, 5, 4, 7, 3, 9, 5]

array([ 8, 14,  6, 18, 10])

array([ 5,  8,  4, 10,  6])

array([False,  True, False,  True, False])

### Reduções numéricas

Algumas operações transformam um conjunto de valores em um único resumo
numérico. NumPy fornece funções para várias dessas reduções.

No array utilizado acima, calcularemos:

- a média;
- a médiana;
- o valor mínimo;
- o valor máximo.

Essas funções recebem o mesmo conjunto de observações, mas resumem aspectos
diferentes de sua distribuição.

In [4]:
print(np.mean(array_de_numeros))
print(np.médian(array_de_numeros))
print(np.min(array_de_numeros))
print(np.max(array_de_numeros))

5.6
5.0
3
9

## 3. Registros representados por dicionários

Um dicionário pode representar uma única **unidade de observação**. Neste
exemplo, cada unidade corresponde a uma obra.

As chaves identificam os campos registrados para essa observação:

- `autor`;
- `titulo`;
- `area`;
- `ano`;
- `n_tokens`;
- `n_types`.

Os valores associados às chaves descrevem a obra correspondente. Quando vários
registros com a mesma estrutura são reunidos em uma tabela, esses campos
correspondem às colunas da tabela.

`autor` e `titulo` identificam ou descrevem a obra; `area` é uma variável
categórica; `ano` registra uma informação temporal; `n_tokens` e `n_types` são
contagens.

As contagens utilizadas neste exemplo são ilustrativas e não correspondem a
medições verificadas das obras citadas.

In [5]:
obra = {
    "autor": "John Tukey",
    "titulo": "Exploratory Data Analysis",
    "area": "estatística",
    "ano": 1977,
    "n_tokens": 125_000,
    "n_types": 13_400,
}

obra

{'autor': 'John Tukey',
 'titulo': 'Exploratory Data Analysis',
 'area': 'estatística',
 'ano': 1977,
 'n_tokens': 125000,
 'n_types': 13400}

In [6]:
print(obra["autor"])
print(obra["titulo"])
print(obra["n_tokens"])

John Tukey
Exploratory Data Analysis
125000

In [7]:
print(obra.keys())
print(obra.values())

dict_keys(['autor', 'titulo', 'area', 'ano', 'n_tokens', 'n_types'])
dict_values(['John Tukey', 'Exploratory Data Analysis', 'estatística', 1977, 125000, 13400])

In [8]:
print(f"{obra['titulo']} foi publicado em {obra['ano']}.")

Exploratory Data Analysis foi publicado em 1977.

## 4. Uma lista de registros

Um dicionário representa uma observação. Uma lista de dicionários pode,
portanto, representar um conjunto de observações.

No exemplo seguinte, cada dicionário descreve uma obra e utiliza o mesmo
conjunto de campos. Essa regularidade permite organizar os registros em uma
estrutura tabular:

- cada dicionário corresponde a uma observação;
- cada campo compartilhado corresponde a uma coluna;
- cada valor ocupa a posição definida por uma observação e uma coluna.

A lista preserva, assim, a distinção entre as obras enquanto mantém a mesma
estrutura de informações para todas elas.

In [9]:
obras = [
    {
        "autor": "John Tukey",
        "titulo": "Exploratory Data Analysis",
        "area": "estatística",
        "ano": 1977,
        "n_tokens": 125_000,
        "n_types": 13_400,
    },
    {
        "autor": "Robert Merton",
        "titulo": "The Normative Structure of Science",
        "area": "sociologia",
        "ano": 1942,
        "n_tokens": 7_600,
        "n_types": 2_650,
    },
    {
        "autor": "Karl Popper",
        "titulo": "The Logic of Scientific Discovery",
        "area": "filosofia",
        "ano": 1934,
        "n_tokens": 155_000,
        "n_types": 12_800,
    },
]
obras

[{'autor': 'John Tukey',
  'titulo': 'Exploratory Data Analysis',
  'area': 'estatística',
  'ano': 1977,
  'n_tokens': 125000,
  'n_types': 13400},
 {'autor': 'Robert Merton',
  'titulo': 'The Normative Structure of Science',
  'area': 'sociologia',
  'ano': 1942,
  'n_tokens': 7600,
  'n_types': 2650},
 {'autor': 'Karl Popper',
  'titulo': 'The Logic of Scientific Discovery',
  'area': 'filosofia',
  'ano': 1934,
  'n_tokens': 155000,
  'n_types': 12800}]

## 5. Estrutura tabular com `DataFrame`


Um `DataFrame` é uma estrutura tabular bidimensional do pandas. Nesta
representação, as linhas correspondem às obras e as colunas correspondem aos
campos compartilhados pelos registros.

`pd.DataFrame()` pode construir essa estrutura diretamente a partir da lista de
dicionários. As chaves dos dicionários determinam os nomes das colunas, e os
valores de cada dicionário preenchem a linha correspondente.

Além das colunas fornecidas pelos dados, o pandas mantém um **índice** para
identificar as linhas. Quando nenhum índice é especificado, são utilizados por
padrão os valores inteiros `0`, `1`, `2`, e assim sucessivamente.

In [10]:
obras_df = pd.DataFrame(data=obras)

obras_df

,autor,titulo,area,ano,n_tokens,n_types
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,13400
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,12800

## 6. Inclusão de uma nova observação

A unidade de observação permanece a obra. Um novo registro com os mesmos campos
pode ser acrescentado à lista `obras` e incorporado à representação tabular.

Como `obras_df` foi construído a partir da lista existente naquele momento,
alterar `obras` não modifica automaticamente o `DataFrame` já criado. Após a
inclusão do novo registro, construímos novamente `obras_df` a partir da lista
atualizada.

In [11]:
nova_obra = {
    "autor": "Machado de Assis",
    "titulo": "Memórias Póstumas de Brás Cubas",
    "area": "literatura",
    "ano": 1881,
    "n_tokens": 64_000,
    "n_types": 9_800,
}

if nova_obra not in obras:
    obras.append(nova_obra)

obras_df = pd.DataFrame(data=obras)

obras_df

,autor,titulo,area,ano,n_tokens,n_types
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,13400
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,12800
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,9800

## 7. Estrutura e inspeção do `DataFrame`

Antes de resumir ou transformar uma tabela, convém estabelecer sua estrutura e
verificar se os dados correspondem ao que esperamos representar.

Algumas propriedades são particularmente úteis nesta etapa:

- `.head()` apresenta as primeiras observações;
- `.shape` informa o número de linhas e colunas;
- `.info()` resume o índice, as colunas, os valores ausentes e os tipos
  computacionais;
- `.describe()` produz resumos descritivos das colunas numéricas.

Essas operações respondem a perguntas diferentes. A inspeção visual verifica
os registros; `shape` descreve as dimensões da tabela; `info()` descreve sua
estrutura computacional; `describe()` resume numericamente algumas variáveis.

In [12]:
obras_df.head()

,autor,titulo,area,ano,n_tokens,n_types
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,13400
1,Robert Merton,The Normative Structure of Science,sociologia,1942,7600,2650
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,12800
3,Machado de Assis,Memórias Póstumas de Brás Cubas,literatura,1881,64000,9800

In [13]:
obras_df.shape

(4, 6)

`shape` retorna uma tupla na ordem `(linhas, colunas)`. Neste caso, `(4, 6)`
indica quatro observações e seis colunas.

O número de linhas corresponde ao tamanho do conjunto de observações
representado no `DataFrame`; o número de colunas corresponde ao número de
campos registrados para cada obra.

Note que `shape` é um atributo, não um método: escreve-se sem parênteses.
`obras_df.shape()` produziria um erro.

In [14]:
obras_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   autor     4 non-null      str
 1   titulo    4 non-null      str
 2   area      4 non-null      str
 3   ano       4 non-null      int64
 4   n_tokens  4 non-null      int64
 5   n_types   4 non-null      int64
dtypes: int64(3), str(3)
memory usage: 324.0 bytes

A saída de `.info()` mostra que `ano`, `n_tokens` e `n_types` são armazenadas
como valores `int64`, enquanto as demais colunas contêm strings. Em versões
anteriores do pandas, colunas de strings aparecem em `.info()` como `object`;
a informação é a mesma.

In [15]:
obras_df.describe()

               ano      n_tokens       n_types
count     4.000000       4.00000      4.000000
mean   1933.500000   87900.00000   9662.500000
std      39.669468   65569.60678   4933.115142
min    1881.000000    7600.00000   2650.000000
25%    1920.750000   49900.00000   8012.500000
50%    1938.000000   94500.00000  11300.000000
75%    1950.750000  132500.00000  12950.000000
max    1977.000000  155000.00000  13400.000000

Por padrão, `.describe()` resume as colunas numéricas. A saída apresenta o
número de observações (`count`), média (`mean`), desvio-padrão (`std`), mínimo,
quartis e máximo. A linha `50%` corresponde à médiana.

Neste exemplo, `n_tokens` e `n_types` são contagens associadas às quatro obras.
`ano` também aparece porque sua representação é numérica, embora resumos como
média e desvio-padrão de anos de publicação não respondam necessariamente a
uma questão substantiva de interesse.

Os valores do exemplo são ilustrativos e o conjunto contém apenas quatro
observações; a saída serve aqui para examinar a estrutura e o comportamento de
`describe()`, não para sustentar conclusões sobre as obras ou suas áreas.

## 8. Colunas derivadas

Uma coluna pode ser definida a partir de valores já armazenados em outras
colunas do `DataFrame`.

Para cada obra, a TTR corresponde à razão entre o número de tipos distintos e
o número de tokens:

$$
\text{TTR}
=
\frac{\text{número de tipos}}{\text{número de tokens}}
$$

As quatro obras apresentam extensões muito diferentes. Como a TTR depende
fortemente do número de tokens, os valores calculados aqui não fornecem uma
base adequada para comparar ou ordenar as obras quanto à variedade lexical.

Neste exemplo, a TTR serve principalmente para expor o cálculo vetorizado de
uma coluna a partir de duas colunas existentes.

In [16]:
obras_df["ttr"] = obras_df["n_types"] / obras_df["n_tokens"]

obras_df[["titulo", "n_tokens", "n_types", "ttr"]]

                               titulo  n_tokens  n_types       ttr
0           Exploratory Data Analysis    125000    13400  0.107200
1  The Normative Structure of Science      7600     2650  0.348684
2   The Logic of Scientific Discovery    155000    12800  0.082581
3     Memórias Póstumas de Brás Cubas     64000     9800  0.153125

Uma nova coluna também pode ser atribuída a partir de uma sequência com o mesmo
número de elementos que o `DataFrame` possui linhas.

Nesse caso, a correspondência é posicional: o primeiro valor é atribuído à
primeira linha, o segundo à segunda linha, e assim sucessivamente. A ordem dos
valores deve, portanto, corresponder à ordem das observações.

In [17]:
n_sentencas = [5_200, 415, 5_950, 3_500]

obras_df["n_sentencas"] = n_sentencas

obras_df[["titulo", "n_sentencas"]]

                               titulo  n_sentencas
0           Exploratory Data Analysis         5200
1  The Normative Structure of Science          415
2   The Logic of Scientific Discovery         5950
3     Memórias Póstumas de Brás Cubas         3500

A razão entre o número de tokens e o número de sentenças fornece o número médio
de tokens por sentença:

$$
\text{tokens por sentença}
=
\frac{\text{número de tokens}}{\text{número de sentenças}}
$$

A unidade de observação continua sendo a obra; a nova variável resume o
comprimento médio de suas sentenças em tokens.

In [18]:
obras_df["tokens_por_sentenca"] = (
    obras_df["n_tokens"] / obras_df["n_sentencas"]
)

obras_df[["titulo", "n_tokens", "n_sentencas", "tokens_por_sentenca"]]

,titulo,n_tokens,n_sentencas,tokens_por_sentenca
0,Exploratory Data Analysis,125000,5200,24.038462
1,The Normative Structure of Science,7600,415,18.313253
2,The Logic of Scientific Discovery,155000,5950,26.050420
3,Memórias Póstumas de Brás Cubas,64000,3500,18.285714

## 9. Classificação condicional com `np.where()`

`np.where()` pode atribuir valores diferentes de acordo com o resultado de uma
condição Booleana.

Com três argumentos, sua estrutura é:

`np.where(condição, valor_se_verdadeiro, valor_se_falso)`

A condição é avaliada para cada observação. Neste exemplo, utilizamos
`n_tokens >= 100_000` para construir uma classificação binária do tamanho das
obras.

O limite de 100.000 tokens é uma decisão didática utilizada para demonstrar a
operação; não corresponde a uma classificação substantiva estabelecida para
extensão textual.

In [19]:
obras_df["classe_tamanho"] = np.where(
    obras_df["n_tokens"] >= 100_000, # condição
    "longo", # se a condição for verdadeira
    "curto", # se a condição for falsa
)

obras_df[["titulo", "n_tokens", "classe_tamanho"]]

                               titulo  n_tokens classe_tamanho
0           Exploratory Data Analysis    125000          longo
1  The Normative Structure of Science      7600          curto
2   The Logic of Scientific Discovery    155000          longo
3     Memórias Póstumas de Brás Cubas     64000          curto

## 10. Filtragem Booleana e seleção com `.loc`

Uma condição aplicada a uma coluna produz uma sequência de valores Booleanos
com uma posição correspondente a cada linha do `DataFrame`. Essa sequência
pode ser utilizada como uma **máscara Booleana** para selecionar observações.

Por exemplo:

```python
obras_df["n_tokens"] >= 100_000
```

avalia a condição separadamente para cada obra. Linhas associadas a `True`
satisfazem o critério; linhas associadas a `False` não o satisfazem.

In [20]:
mascara = obras_df["n_tokens"] >= 100_000

mascara

0     True
1    False
2     True
3    False
Name: n_tokens, dtype: bool

In [21]:
obras_df[mascara]

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas,tokens_por_sentenca,classe_tamanho
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,13400,0.107200,5200,24.038462,longo
2,Karl Popper,The Logic of Scientific Discovery,filosofia,1934,155000,12800,0.082581,5950,26.050420,longo

A filtragem preserva os índices das observações selecionadas. Por isso, as duas
linhas resultantes mantêm os índices `0` e `2`, em vez de receberem
automaticamente novos índices `0` e `1`.

A máscara também pode ser escrita diretamente dentro dos colchetes quando não
precisamos reutilizá-la.

In [22]:
obras_df[obras_df["area"] == "estatística"]

,autor,titulo,area,ano,n_tokens,n_types,ttr,n_sentencas,tokens_por_sentenca,classe_tamanho
0,John Tukey,Exploratory Data Analysis,estatística,1977,125000,13400,0.1072,5200,24.038462,longo

### Seleção de linhas e colunas com `.loc`

`.loc` permite especificar, na mesma operação, quais linhas e quais colunas
devem ser selecionadas. Sua forma geral é:

```python
df.loc[seletor_de_linhas, seletor_de_colunas]
```

Os seletores utilizados por `.loc` são baseados nos rótulos do `DataFrame`.
Para as linhas, também podemos fornecer uma máscara Booleana.

No exemplo seguinte:

- a condição sobre `n_tokens` seleciona as observações;
- a lista de nomes seleciona as colunas que permanecerão no resultado.

In [23]:
obras_df.loc[
    obras_df["n_tokens"] > 50_000,
    ["autor", "titulo", "n_tokens", "n_types"],
]

              autor                             titulo  n_tokens  n_types
0        John Tukey          Exploratory Data Analysis    125000    13400
2       Karl Popper  The Logic of Scientific Discovery    155000    12800
3  Machado de Assis    Memórias Póstumas de Brás Cubas     64000     9800

## 11. Ordenando observações

`.sort_values()` reorganiza as linhas de um `DataFrame` segundo os valores de
uma ou mais colunas.

O argumento `by` identifica a coluna utilizada como critério de ordenação.
`ascending=True` produz ordem crescente; `ascending=False`, ordem decrescente.

A operação modifica a ordem das observações apresentadas, não seus valores.
Os índices originais são preservados. `sort_values()` retorna um novo objeto:
`obras_df` permanece inalterado, e a tabela original só mudaria se o resultado
fosse atribuído de volta a `obras_df`.

In [24]:
obras_df[["titulo", "n_tokens"]].sort_values(
    by="n_tokens",
    ascending=False,
)

                               titulo  n_tokens
2   The Logic of Scientific Discovery    155000
0           Exploratory Data Analysis    125000
3     Memórias Póstumas de Brás Cubas     64000
1  The Normative Structure of Science      7600

In [25]:
obras_df[["titulo", "ano"]].sort_values(
    by="ano",
    ascending=True,
)

                               titulo   ano
3     Memórias Póstumas de Brás Cubas  1881
2   The Logic of Scientific Discovery  1934
1  The Normative Structure of Science  1942
0           Exploratory Data Analysis  1977

## 12. Frequências absolutas

Para uma variável categórica, a frequência absoluta de uma categoria
corresponde ao número de observações classificadas nessa categoria.

`.value_counts()` calcula essas frequências para os valores distintos de uma
coluna. Como a unidade de observação neste `DataFrame` é a obra, os resultados
indicam quantas obras pertencem a cada categoria.

Aplicaremos a operação primeiro a `area` e depois à variável derivada
`classe_tamanho`.

In [26]:
obras_df["area"].value_counts()

area
estatística    1
sociologia     1
filosofia      1
literatura     1
Name: count, dtype: int64

In [27]:
obras_df["classe_tamanho"].value_counts()

classe_tamanho
longo    2
curto    2
Name: count, dtype: int64

## 13. Agrupando e agregando

Agrupamento divide as observações segundo os valores de uma ou mais variáveis
categóricas. Uma função de agregação pode então resumir outra variável
separadamente em cada grupo.

Uma forma básica dessa operação em pandas é:

```python
df.groupby("grupo")["variavel"].metrica()
```

A expressão contém três componentes:

1. `groupby("grupo")` define os grupos;
2. `["variavel"]` seleciona a variável que será resumida;
3. `.metrica()` especifica a medida calculada em cada grupo.

Neste exemplo, `classe_tamanho` possui duas categorias, `curto` e `longo`, com
duas obras em cada grupo. Os resultados são, portanto, resumos descritivos
dessas quatro observações.

In [28]:
obras_df.groupby("classe_tamanho")["tokens_por_sentenca"].mean()

classe_tamanho
curto    18.299484
longo    25.044441
Name: tokens_por_sentenca, dtype: float64

### Agregações nomeadas

`.agg()` permite calcular várias medidas na mesma operação. Com agregações
nomeadas, cada coluna do resultado é especificada pela forma:

```python
nome_do_resultado=("coluna_original", "funcao")
```

Podemos, por exemplo, contar o número de observações em cada grupo e resumir
`tokens_por_sentenca`.

Como `classe_tamanho` foi definida a partir de `n_tokens`, qualquer resumo de
`n_tokens` por essas categorias deve ser interpretado com cuidado: a diferença
entre os grupos nessa variável decorre, em parte, da própria regra utilizada
para construí-los.

In [ ]:
obras_df.groupby("classe_tamanho").agg(
    n_obras=("titulo", "count"),
    média_tokens=("n_tokens", "mean"),
    média_tokens_por_sentenca=("tokens_por_sentenca", "mean"),
    médiana_tokens_por_sentenca=("tokens_por_sentenca", "médian"),
)

,n_obras,media_tokens,media_tokens_por_sentenca,mediana_tokens_por_sentenca
classe_tamanho,,,,
curto,2,35800.0,18.299484,18.299484
longo,2,140000.0,25.044441,25.044441

A coluna `média_tokens` ilustra o problema apontado acima: a diferença entre os grupos é consequência direta da regra que os definiu.

A coluna `média_tokens` ilustra o problema apontado acima: como os grupos foram
definidos a partir de `n_tokens`, a diferença entre eles nessa variável é
consequência direta da regra que os construiu, e não um achado sobre os dados.

Cada grupo contém apenas duas obras. Nesse caso particular, média e médiana de
`tokens_por_sentenca` coincidem, pois a médiana de duas observações é definida
como a média dos dois valores centrais.

Esses resultados descrevem exclusivamente o pequeno conjunto ilustrativo
utilizado neste encontro. O objetivo da agregação é expor a estrutura da
operação, não comparar classes de obras substantivamente.